### ISSUE TITLE
Peer review team B

### ISSUE THREAD

**Issue by Raalit00** [SvenWeiss-HDM/Projektgruppe_A#6]
### Peer review team

- Peer review by: Group B
- Names of team members that participated in this review: Niels-Janos Simmet & Raghid Allaham

### Goal of the project

1) Predict if two people of opposite sex are having a "match" based on certin attributes.
2) Find out what are the most importent attributes to get a match in opposite sex speed dating.
3) Proof of correctness of the following hypotheses:
-   Survey participants who both have the specific characteristics samerace and opposite gender tend to achieve more matches
-   Survey participants with a higher income tend to achieve more matches than survey participants with a lower income
-   Achieving matches because of having the same specific characteristics occur in both sexes
-   Three weeks after the event, males called women more often

### Data

Fisman et al. conducted a survey regarding speed dating habits and collected 8,000 observations.
These data were collected from participants in experimental speed dating events held in 2002-2004. In these events, participants had a four-minute "first date" with each other participant of the opposite sex. At the end of the four minutes, participants were asked if they would like to see their date again. They were also asked to rate their date on some characteristics.

Data: https://perso.telecom-paristech.fr/eagan/class/igr204/datasets/SpeedDating.csv

- Data Description is good and sufficient
- In the introduction talked about "willingness to date has decreased, dating is too expensive and time consuming..." would be nice to state a source here.
- Showing the whole data set once could help the reader understand why you chose your subset of variables. Understandably with >150 columns that is not really feasable.
- A short explanation of how the data was collected would be helpful.
	- Were the dates randomly assigned? Or was an attempt made to allocate suitable participants on the basis of certain characteristics during the allocation process?
	- Did only heterosexuals participate in the study? If the proportion of homosexuals is higher in one gender, there could be a bias in exclusively heterosexual pairings during SpeedDating.

### Descriptive statistics and exploratory data analysis
- The graphics are mostly well done and look good.
- The code is written mostly clear and understandable
- Does one observation equal the answers from one person regarding one date or the answer of both persons regarding one date or a summary of the whole event from one persons perspective? 
	- Dependent on that I don't see how adding the calls makes sense
- Could the discrepancy between them_call and you_call be explained by the fact that not all participants answered the question? As half of the subjects didn't answer that question. Interesting would be, if both sexes didn't answer that question to the same percentage or if i.e. mostly women didn't answer that question.
- Why is the Descriptiv statistics done only on the Train Data Set? Is this on purpose?
- Gender differences per Attribute is not displaying any output for me. I think because you are setting the Graph as c1 but never call it again
- Attribute importance to get a match Graph: Here I would prefer to size the circles relative instead of absolute, as there is a big absolute difference between match/no match that disorts the graphic.
- I would do Exploratory Data Analysis before the descriptive statistics
- Attribute correlation graph is hard to interprete due to the graphics, maybe you could rather use a heat map of some sort instead to make it clearer?
- Correlation Table: use a different gradient to also highlight strong negative correlations. With that gradient high positiv is blue and high negative is white even though the absolutes matter.

### Classification Model
- The graphics are well done
- The code is understandable (a few more comments would be cherry on the cake) and statistical methods are applied correctly
- I liked the experimentation with different thresholds 
- I don't see the point in using a synthetically balanced data set. You are no longer refering to actual data that was gathered but a hypothetical study.

### Regression Model
- The graphics are well done
- The code is understandable (a few more comments would be cherry on the cake) and statistical methods are applied correctly
- I like that you used SelectKBest to determine the most influential features for regression
- The comparison of the models at the end is great. Maybe you could add a naive model as benchmark to show the improvement
- Reflecting on the Feature importance is insightful and a nice touch

### Conclusion
- You state that there is a negative correlation for being the same gender. Where did you show that? Weren't all the pairings heterosexual?
- Could you do types like Athletes, Religious persons, ... or is the data not sufficient for that?
- Why didn't you investigate 2 of 4 Hypotheses in detail. Why did you set them in the first place then? Maybe you can explain your reasoning, i.e. there not enough data to investigate in detail
- Three weeks after the event males called women more often. Can you do a significants test here i.e. Students T Test? With what confidence can you say that. Especially regarding the percentage of NaN values for that question.

### Possible improvements

- In addition, you could have separated the data by gender to see how differently genders react to characteristics. (example hypothesis: men don't like it when a woman is ambitious.) plot a correlation matrix per gender and examine which attributes are most important to a woman and which attributes are important to a man. Doing so would answer the research question: "Do these specific characteristics occur in both sexes?". 

- You could try including more / other variables in your models and see if the performance changes. This could lead to a different conclusion, or you could use backward or forward selection to select the variables

### Presentation

- The most interesting part is how to answer the research question.
 Is something similar already being used by dating apps? If so, what kind of data are they using?
 
- And what could be done to further improve the models to compare the two. What could be the next steps for a follow up project.

### Further comments
- Even though critical comments may seem to overweigh in our review. That is not the actual case, your analysis is well done and comprehensive. It is just easier to point out things that could be improved rather than things that are already great :)

**Comment by lz039** [comment]
Thank you very much for your comments, we took many of them into account for our final report and presentation.
